### PR TITLE
Switch to flit build backend

### LINKED ISSUE #704: Use a flit-based backend?
I'd like to contribute a flit-based backend, which I think would greatly simplify things.

Instead of a 1000 line `setupbase.py` we could use an in-tree backend similar to what I tried in https://github.com/ipython/ipykernel/pull/927.

I had to abort that one because `ipykernel` ships with multiple top level entities, but `ipyparallel` does not.

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #704 

- [x] Make sure the labextension and nbextension are properly installed from sdist and wheel

### CODE REVIEW

**Comment by blink1073** [comment]
@minrk, interesting limitation here.  `setuptools` allows prereleases to satisfy version [constraints](https://github.com/pypa/setuptools/blob/315f1751052dee408b543b202aab0a3e8209a632/pkg_resources/__init__.py#L3131), which is not technically correct.  `flit` uses the more correct version constraint.  So, we end up with a `pyzmq` constraint that we cannot satisfy.   We could potentially install without `--pre` and then have a script that explicitly installs all of the direct dependencies with `--pre` .  That script could go in `maintainer-tools`, similar to the minimum version handler.  WDYT?

**Comment by minrk** [comment]
I don't quite understand how flit is involved in resolving prereleases. Isn't pip used for install?

I don't care too much about preleases (certainly not prerelease pyzmq which isn't used) in the build step, but I do think it's important to test against prereleases.

I also think it's just not true that allowing prereleases to satisfy constraints is incorrect. According to [PEP440](https://peps.python.org/pep-0440/#inclusive-ordered-comparison), _inclusive_ ordering (`>=`) should accept prereleases. Prereleases are only excluded for _exclusive_ ordering (`>`). Whatever code is rejecting that is not doing the right thing.

**Comment by minrk** [comment]
Tested the wheel from the actions artifacts. Extensions are working as before.

Thanks!

**Comment by blink1073** [comment]
Sweet, thanks for the assist!

**Comment by minrk** [comment]
Thanks! Going to make a release next week with the various build fixes.

**Pull request merged**
