### PR TITLE
use build:prod for labextension, lab trove classifiers

### PR DESCRIPTION
**Pull request by bollwyvl**
Hi folks, and as always, thanks for ipyparallel!

This ensures that windows-friendly (e.g. short) paths are created during the pip-managed labextension build, as it was [getting some users on that platform down](https://github.com/conda-forge/ipyparallel-feedstock/issues/62#issuecomment-984163082).

While I was in there, I added some of the new jupyter(lab(extension))-specific trove classifiers.

### CODE REVIEW

**Comment by minrk** [comment]
Thanks! Still new to the whole labextension world.

**Comment by bollwyvl** [comment]
No worries! I wish we had some better answers, but at least we can solve
emergent issues at build time (if not find them) instead of on everyone's
machine, and then be more sure everyone's got the same assets.

We should probably figure out a way to make it work in retro/nb7...

**Comment by minrk** [comment]
Yeah, maybe so. I'm also okay with the clusters being a lab thing, though. With the new Python API for starting clusters, I think starting clusters from clicky things is less important because `ipcluster` in a terminal is not the only alternative, most examples should be fully self-contained in a notebook.

**Comment by bollwyvl** [comment]
>  okay with the clusters being a lab thing

I guess that's the point on the [NB7 JEP](https://github.com/jupyter/enhancement-proposals/pull/79): there's what we (contributors, maintainers, etc) might _want_, after having learned more over the last decade, and what we (admins, users, etc.) have come to expect over that decade. 

I could see the case of there being some existing internal documentation/course material out there that says, _Open Tree_, _Open the clusters Tab_, _Type in this hard-coded IP Address_, yadda, yadda.

**Comment by minrk** [comment]
Yeah, we can certainly do that if there's demand. Presumably it shouldn't be too hard to make a different 'view' from the same js more akin to the clusters tab.

I will say this, though: I don't think we would have made the clusters tab if we had the Python API we have in 7.0.

The clusters tab predates even having terminals in the notebook, so it was literally impossible to start clusters without it, unless you had a separate terminal connection, which wasn't always available. Even as it is now, I think creating clusters with `ipp.Cluster()` is a _better_ experience than the clusters tab, pretty much across the board.

Users are always free to disagree :)

**Comment by bollwyvl** [comment]
> Users are always free to disagree :)

Yeah, guess we should hoist this out of a closed PR :rofl: 

will hoist to an issue!

**Pull request merged**
