### PR TITLE
Fixes and test coverage for coalescing broadcast views

### PR DESCRIPTION
**Pull request by minrk**
avoids error: got unknown result: 098dcdc9-326e56d369825c8d5c63034e_3911_1_3a745ca5-2189263bff5e0e0520d62493 with execute (including `%px`) when using a coalescing broadcast view.

and make sure we have test coverage for `BroadcastView(is_coalescing=True)`

### CODE REVIEW

**Review by sahil1105 — APPROVED** [review]
Looks good to me, thanks @minrk!
So basically it was just a small bug on the client side?

**Comment by minrk** [comment]
Yeah, part of the updates in apply when coalescing didn't get copied over to execute. Looks like there are a few other things that don't work yet with coalescing. I'll go through those and see what else needs to catch up, now that we have full coverage of coalescing broadcast

**Comment by minrk** [comment]
While this fixed `%px`, there's a deeper issue that the coalescing replies do not always preserve the order of results. Working on that now.

**Comment by minrk** [comment]
There's a bigger task in getting coalescing to work, because more information is discarded than I realized. The coalescing replies only preserve results themselves, not other metadata, which means several tests won't pass.

I've fixed a few things I found, but mostly disabled coalescing for several operations, including execute. Mainly this means that `%px` will ignore `is_coalescing=True` and always use False.

**Pull request merged**
