### PR TITLE
man page files moved from ipython

### PR DESCRIPTION
**Pull request by takluyver**
I don't know if these are worth keeping - they basically just say 'see --help'. But I'm moving them out of IPython, and this is the obvious place for them to go if we do keep them.

### CODE REVIEW

**Comment by minrk** [comment]
I'd actually vote for leaving them out.

**Comment by takluyver** [comment]
Fair enough. I don't feel strongly about this. Do you want to close this, or give other people a chance to weigh in?

**Comment by minrk** [comment]
Let's ping the list.

**Comment by Carreau** [comment]
Didi we ping the list ?

**Comment by tomspur** [comment]
The man pages could also be created with [`python setup.py build`](https://andialbrecht.wordpress.com/2009/03/17/creating-a-man-page-with-distutils-and-optparse/) to match the output of `--help`?

**Comment by minrk** [comment]
@tomspur Is there a sufficiently near-perfect translator for plain-text markup to manpage format?

**Comment by tomspur** [comment]
I read about [help2man](https://www.gnu.org/software/help2man/), which is also mentioned in the [Fedora wiki](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#Manpages), but I never tested it myself...

**Comment by fperez** [comment]
Given that they basically amount to quasi-auto-generated information but done by hand, it would be nice to have them be actually auto-generated... I recall ages ago taking a stab at auto-generating them precisely because it bothered me so much to have that information written by hand in two places, but I never quite got it to work.

I'd like to hear from @juliantaylor, what's the impact if we do this for downstream packages? Are they already set up to auto-generate clean man pages from `--help`?  If so, maybe we can just delegate that job to the distros...

**Comment by juliantaylor** [comment]
I don't think many distros currently autogenerate them given that its not officially supported by you.
Though if these files disappear it might happen.
You do get decent results with `rst2man`, probably better than the currently existing stubs.
Providing these generated files via your source tarball would be nice to have, though distros could do this themselves too.

**Comment by fperez** [comment]
I'm ok removing them for now, it will be incentive for us, or someone else, to auto-generate them properly.

**Comment by minrk** [comment]
Thanks, closing then.

**Pull request closed without merging**
