### PR TITLE
DOC: reformat docstrings  + misc fixes

### PR DESCRIPTION
**Pull request by Carreau**
DOC: Autoreformatting to confirm to numpydoc

Many trailing space, but spaces before colon in parameters are
meaningful.

a couple of typos also.

### CODE REVIEW

**Comment by Carreau** [comment]
Ah, it conflict because it's now main so I need to rebase...

**Comment by Carreau** [comment]
Actually was easier to re-run the reformatter.

**Comment by minrk** [comment]
@Carreau is this perhaps an autoformatter to add to pre-commit?

**Comment by Carreau** [comment]
> @Carreau is this perhaps an autoformatter to add to pre-commit?

https://github.com/carreau/velin not stable yet, once it's stable why not. Would happily to get your feedback on it.

**Pull request merged**
