### PR TITLE
Cluster Python API

### LINKED ISSUE #22: Feature proposal: Launch ipcluster from python
For simple parallelization requirements on a single host it is often an extra burden (especially when designing APIs) to require the user to launch `ipcluster`. If instead I could also launch these from within my Python library it could be a very nice replacement for `multiprocessing` which supports this mode. Specifically, if my library is using multiprocessing the user doesn't have to care about anything and get single-machine parallelization for free. The problem is that `multiprocessing` sucks and I'd much rather use `ipyparallel` for this as well.

I suppose there might be an unsupported way to do this already by importing `ipcluster` somehow.

Anyway, I think that would be useful for certain problems.

### LINKED ISSUE #94: remote restart ipengine
I think this actually a pretty old idea, but I was wondering if there has been any movement on it.  

In the same way you can restart a kernel in a notebook, it would be awesome if you could restart an ipengine.  My understanding is that this would require a nontrivial rewrite of the engine, involving an entire extra monitoring process that just isn't there right now. 

Does this seem like something likely to be implemented?  If I took a crack at it, would that be helpful?  Or is there another plan...

### LINKED ISSUE #216: If task is running, how to forcing  shut down the engine?
Client.shutdown need to wait for task to finish, and then shut down the engine
If task is running, how to forcing  shut down the engine?

### LINKED ISSUE #241: Daemonize after engines start
Currently, `ipcluster` can be run in the foreground or in the background using the `--daemonize` option. However, this daemonizing appears to happen immediately at startup. So if I run something like:
```bash
#!/bin/bash

ipcluster-3 start -n 4 --daemonize
python3 <<EOF
from ipyparallel import Client
client = Client()
print(client[:])
EOF
```
then the script fails because the engines are not available (`ipyparallel.error.NoEnginesRegistered`). Inserting a `sleep 5` will fix it because the engines will have started, but this is basically a guess-and-hope-it-works approach.

It would be really nice if `ipcluster` would wait to background itself until after the engines have started instead.

### LINKED ISSUE #243: splitting engines into smaller groups
I'm trying to use ipyparallel to run a Monte Carlo simulation with thousands of runs. If I attempt to start, say, 500 engines (5 to a node) on SLURM, the current architecture attempts to allocate 100 nodes at once, leading to long waits. I was looking at how best to modify this to split the these into chunks that can start independently of one another, and thus get going sooner.

It would be ideal if there were config options for batch systems:
- (int) engines_per_node, default 1
- (bool) separate_engine_jobs, default False (legacy mode)

If separate_engine_jobs is True, queue ((N/engines_per_node) + (1 if N % engines_per_node else 0)) jobs  with each setting ntasks={engines_per_node}. Of course, this would require tracking a list of job IDs to kill them when stopping the cluster.

I tested this by manually calling sbatch repeatedly to start 5 engines/node. The additional engines were seen by the schedulers when they start running, as I'd hoped. The only problem was that stopping the cluster didn't kill the separately launched engines.

The simplest approach for me would be to write this in my app that wraps all the ipyparallel stuff, but I thought it sounded like a good general feature, thus this note.

### LINKED ISSUE #460: [Feature] Cluster Manager Python API
It would be good to have a ClusterManager object which can start the engines using MPI, keep tabs on the `mpiexec` process, report crash to controller (with exit code, etc.), etc. This should also remove the need for heartbeats since `mpiexec` already monitors health of the engines. In case of a crash, we can quickly inform the controller (which can then inform the client).
We can also provide pythonic APIs to start and restart engines. Users could provide additional parameters for `mpiexec` when starting the engines, like rank-placement (round-robin, etc.) and so on.
Interrupts can be handled through this object as well (send signal to `mpiexec`, etc.). 
Deleting the object should stop the engines and clean up the memory. Running the code again would start a new set of engines.

---

EDIT: linked issues: #22, #44, #216, #243, #241

### PR DESCRIPTION
**Pull request by minrk**
Cluster is a Python API for starting/stopping/signaling controllers and engines. It is basically rewriting IPClusterApp as a simpler object with a reusable API. It's a fully asyncio API natively, with automatic `_sync` methods that provide synchronous versions of everything that should work both inside and outside asyncio.

TODO:

- [x] create cluster subpackage
- [x] Cluster can start/stop/signal engines, connect clients, be used as a context manager, etc.
- [x] basic tests for Cluster
- [x] simplify ipcluster cli to build on Cluster API
- [x] (more) Cluster tests
- [x] set up mpi on CI (probably means conda)
- [x] ClusterManager for multiple Clusters
- [ ] serialize cluster to/from dict for e.g. `ipcluster stop/list` (#480)
- [x] work out signature / options, etc.
- [ ] work out distribution of connection info  (#483)
- [ ] signaling single engines (#475)

closes #22
closes #216
closes #243
closes #241
closes #460
closes #94

### CODE REVIEW

**Comment by minrk** [comment]
@sahil1105 it's not quite ready, but the basics are here if you want to start reviewing. In particular, you can check out the [example notebook](https://nbviewer.jupyter.org/github/minrk/ipyparallel/blob/cluster-manager/examples/Cluster%20API.ipynb) walking through:

- starting/stopping clusters
- using them as context managers
- starting engines with MPI
- interrupting and restarting engines

**Comment by minrk** [comment]
@sahil1105 I think this is reasonably complete for a first draft. I'm still debugging little discrepancies between my environment and CI, but everything's working for me locally

**Comment by minrk** [comment]
@sahil1105 I think this is about ready to go for a first draft if you'd like to review. It's working and relatively complete. I've opened issues for the follow-up tasks to do after landing this.

I'm still ironing out the kinks of testing MPI on CI (everything passes for me locally)

**Comment by minrk** [comment]
All tests are passing now

**Comment by sahil1105** [comment]
> @sahil1105 it's not quite ready, but the basics are here if you want to start reviewing. In particular, you can check out the [example notebook](https://nbviewer.jupyter.org/github/minrk/ipyparallel/blob/cluster-manager/examples/Cluster%20API.ipynb) walking through:
> 
> * starting/stopping clusters
> * using them as context managers
> * starting engines with MPI
> * interrupting and restarting engines

Will do. Thanks!

**Review by sahil1105 — COMMENTED** [review]
@minrk Sorry about the delay, looks great to me, thanks!
Couple of questions:
1. Is there a way/API to send signal to`mpiexec` itself if needed? I know we're handling SIGINT, etc. using a signal handler on each process without involving `mpiexec` which makes sense, but we might for instance send a `SIGUSER` to `mpiexec` which the application could receive and handle.
2. When we restart NB kernel (w/o calling `stop_cluster()`), are all controller/engine resources cleaned up or left dangling (and if so what's the best way to clean them)?
3. For certain implementation, like MPI, when the engines are started using a Launcher, do we need heartbeats between engine and controller? Also, if the `mpiexec` process dies while running user code, will the user (client) get notified immediately (since the launcher has a handle on the mpiexec process), or will it still need to wait until enough heartbeats have missed?

**Comment by minrk** [comment]
> Is there a way/API to send signal to mpiexec itself if needed? 

Yes, `signal_engines` does exactly this. I still think we should implement sending signals to engines directly for a host of reasons (mpiexec's own poor signal handling among them). That would become a *client* method instead of a *cluster* method, though, so we wouldn't lose the ability to signal mpiexec from the Launcher. That approach is not yet implemented, though (#475).

> When we restart NB kernel (w/o calling stop_cluster()), are all controller/engine resources cleaned up or left dangling (and if so what's the best way to clean them)?

They *should* be, but it cannot be assumed because cleanup code cannot be guaranteed to run (e.g. killed with SIGKILL, no cleanup events can be assumed to have run). I can work on cleaning up as often as possible (e.g. with atexit, which I started working on already, but haven't pushed it yet). Ultimately, we need #480 to interact with clusters not started by the current process. Actions would include:

- listing running clusters
- connecting to a cluster started previously
- shutting down clusters not started by this process

> For certain implementation, like MPI, when the engines are started using a Launcher, do we need heartbeats between engine and controller?

That's a tricky one. If a launcher can be trusted to be notified, yes. mpiexec is not such a launcher in general, because a process can begin exiting at which point it becomes unresponsive and should be considered 'dead'. The hearbeat mechanism should catch this, but mpiexec will not because the process still exists and/or has begun 'cleanly' shutting down via MPI_Finalize. mpiexec only notifies about "abnormal" exit, i.e. exit without finalize.

So relying on mpiexec can mean engines are *less* likely to be notified of shutdown than the current mechanism.

We can, however, at least send the same notification about engine shutdown in all the cases where mpiexec *does* exit, which should have most of the benefit–improved responsiveness–without the cost of removing it–missed shutdown events. I've opened #491 to track this.

**Comment by sahil1105** [comment]
> > Is there a way/API to send signal to mpiexec itself if needed?
> 
> Yes, `signal_engines` does exactly this. I still think we should implement sending signals to engines directly for a host of reasons (mpiexec's own poor signal handling among them). That would become a _client_ method instead of a _cluster_ method, though, so we wouldn't lose the ability to signal mpiexec from the Launcher. That approach is not yet implemented, though (#475).
> 

Oh ok, makes sense. Thanks.

> > When we restart NB kernel (w/o calling stop_cluster()), are all controller/engine resources cleaned up or left dangling (and if so what's the best way to clean them)?
> 
> They _should_ be, but it cannot be assumed because cleanup code cannot be guaranteed to run (e.g. killed with SIGKILL, no cleanup events can be assumed to have run). I can work on cleaning up as often as possible (e.g. with atexit, which I started working on already, but haven't pushed it yet). Ultimately, we need #480 to interact with clusters not started by the current process. Actions would include:
> 
> * listing running clusters
> * connecting to a cluster started previously
> * shutting down clusters not started by this process
> 

Got it, makes sense. Yes, I did notice that sometimes there are lingering processes sometimes, but a simple bash script to terminate all ipcontroller processes could take care of that for now.

> > For certain implementation, like MPI, when the engines are started using a Launcher, do we need heartbeats between engine and controller?
> 
> That's a tricky one. If a launcher can be trusted to be notified, yes. mpiexec is not such a launcher in general, because a process can begin exiting at which point it becomes unresponsive and should be considered 'dead'. The hearbeat mechanism should catch this, but mpiexec will not because the process still exists and/or has begun 'cleanly' shutting down via MPI_Finalize. mpiexec only notifies about "abnormal" exit, i.e. exit without finalize.
> 

Ah ok, understood.
Yes, I was interested in the abnormal exit case where one (or more) processes exit and MPI closes all of them and exits with code 6 or code 9 or something.

> So relying on mpiexec can mean engines are _less_ likely to be notified of shutdown than the current mechanism.
> 
> We can, however, at least send the same notification about engine shutdown in all the cases where mpiexec _does_ exit, which should have most of the benefit–improved responsiveness–without the cost of removing it–missed shutdown events. I've opened #491 to track this.

Agreed. Sounds good, thanks!

**Comment by minrk** [comment]
Thanks for the review, @sahil1105!

**Pull request merged**
