### PR TITLE
test bind_kernel

### PR DESCRIPTION
**Pull request by renewang**
PR for issue  [#164](https://github.com/ipython/ipyparallel/issues/164)  
Also added a test case in test_apps.py

### CODE REVIEW

**Comment by minrk** [comment]
Sorry, forgot to close #164 when I merged #166. This has already been fixed. Would you like to rebase this PR so it just adds the test?

**Comment by renewang** [comment]
I'm trying to identify the resource warning with my environment and trying identify the problem. I'm still trying going through document for pyzmq and survey some other socket testing techniques. Any help and suggest is welcome. Thanks

**Comment by renewang** [comment]
The build failure for python 2.7.9 is due to no mock library (which is a standard library in python3.+). I was wondering what I should to comply your policy (or maybe give me a quick link for reference). Should I just use arbitrary third-party library to complete python2.7 version of test? Thanks

**Comment by minrk** [comment]
Sorry for being unresponsive. It's fine to add mock for testing on Python 2.

In the future, it would be useful to avoid merging upstream branches several times into a PR. You can use `git rebase` to resolve merge conflicts.

**Pull request merged**
