### PR TITLE
Switch to hatch backend

### PR DESCRIPTION
**Pull request by blink1073**
[Hatch](https://hatch.pypa.io/latest/) is now part of the pypa, and offers us some niceties:

- Allows us to have a more simplified build script
- Allows us to use multiple paths for `data` files (called `shared` files)
- Avoids this [error](https://github.com/pypa/pip/issues/11110) which is causing all builds to fail on [main](https://github.com/ipython/ipyparallel/runs/6437846884?check_suite_focus=true) and in `ipykernel` [downstream tests](https://github.com/ipython/ipykernel/runs/6437885383?check_suite_focus=true)
- Uses `.gitignore` to determine what files to include by default

While `hatch` does allow for dynamic versioning, this PR uses static versioning with `tbump` to avoid any parsing issues.

### CODE REVIEW

**Comment by blink1073** [comment]
I hit a snag where we can't include `ipyparallel/labextension` in the dist files, opened https://github.com/pypa/hatch/issues/243

**Comment by blink1073** [comment]
Found a workaround, not too bad:

```toml
[tool.hatch.build.force-include]
"./ipyparallel/labextension" = "ipyparallel/labextension"
```

So that way it respects `.gitignore` except where we have to override it, and the wheel only include the data files and the package.

**Comment by blink1073** [comment]
Updated to latest `hatchling` so we can use `artifacts` config instead of `force_include`.

**Comment by minrk** [comment]
Nice, thanks!

**Pull request merged**
