### PR TITLE
add Client.become_distributed

### PR DESCRIPTION
**Pull request by minrk**
Turns current IPython cluster into a [distributed](https://distributed.readthedocs.org) cluster:

- starts Scheduler on the Hub
- starts Worker on each engine
- returns Executor connected to the Scheduler

This was super easy, thanks @mrocklin!

Questions for @mrocklin:

- Should there be different default args to the constructor(s)?
- Is the worker or scheduler more likely to get non-default constructor args?
- Anything else to consider?

### CODE REVIEW

**Comment by mrocklin** [comment]
> Should there be different default args to the constructor(s)?

What's here looks great to me.  I appreciate that it's easy to pass keyword arguments through and that we'll defer to the defaults on the worker itself, so this will track changes well.

> Is the worker or scheduler more likely to get non-default constructor args?

Probably the worker

> Anything else to consider?

You might want to consider allowing `Nanny`s instead of `Worker`s.  Everything should work the same.   I often have a keyword argument here like `Worker=Worker`.  Supporting nannys would allow a few operations, like `e.restart()` and the use of one "worker" to use multiple processes rather than threads.  
It would also offload computation from the IPython client process.

I would actually find a lot of value to using IPython parallel to help me debug the workers when things go wrong.  I would love, for example, to go and inspect the scheduler and worker's data directly when something odd happens.  It might be useful to put basic instructions for how to do this on the `become_distributed` method.

**Comment by minrk** [comment]
I filled it out a bit more, adding a `nanny` arg for creating with Nanny instead of just Worker. I also included an example of accessing `Worker.data` after a failure, but I'm afraid I couldn't do much more interesting than that. Is there a good way to ask the Executor or Future where a given task failed and/or succeeded?

**Comment by mrocklin** [comment]
Oh that's very cool.  There is a way to see where the future landed, but it's not very user accessible.  I'm refactoring things internally now and will add more pleasant function hooks for this in a few days.  I recommend that I edit the example notebook in a future PR.

**Comment by minrk** [comment]
Sounds great! I'll add some basic exercise for this in tests, then merge away.

**Pull request merged**
